import numpy as np
import scipy.stats as stats
np.random.seed(188)
group1 = np.random.rand(100)
group2= np.random.rand(100)
group3 = np.random.rand(100)
avg1 = np.mean(group1)
avg2 = np.mean(group2)
avg3 = np.mean(group3) 
median1 = np.median(group1)
median2 = np.median(group2)
median3 = np.median(group3)
ptp1 = np.ptp(group1)
ptp2 = np.ptp(group2)
ptp3 = np.ptp(group3)
var1 = np.var(group1)
var2 = np.var(group2)
var3 = np.var(group3)
std1 = np.std(group1)
std2 = np.std(group2)
std3 = np.std(group3)
mode1= stats.mode(group1)
mode2= stats.mode(group2)
mode3= stats.mode(group3)
cov = np.cov(group1, group2)
corrcoef= np.corrcoef(group1, group2)
print('Group 1: Average:', avg1, 'Median:', median1, 'Range:', ptp1, 'Variance:', var1, 'Standard Deviation:', std1, 'Mode:', mode1)
print('Group 2: Average:', avg2, 'Median:', median2, 'Range:', ptp2, 'Variance:', var2, 'Standard Deviation:', std2, 'Mode:', mode2)
print('Group 3: Average:', avg3, 'Median:', median3, 'Range:', ptp3, 'Variance:', var3, 'Standard Deviation:', std3, 'Mode:', mode3)
print('Covariance:', cov)
print('Correlation Coefficient:', corrcoef)